[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[invariant]
runs = 40
depth = 128
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
